# Generated by Django 4.1.1 on 2022-09-15 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('category_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Major1st',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Major1', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Major2nd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Major2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
                ('major_1st', models.ManyToManyField(related_name='major1', to='PostApp.major1st')),
                ('major_2nd', models.ManyToManyField(related_name='major2', to='PostApp.major2nd')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='PostApp.category')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='PostApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.IntegerField()),
                ('like_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='PostApp.post')),
                ('like_user', models.ManyToManyField(related_name='likes', to='PostApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='PostApp.user')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='PostApp.post')),
            ],
        ),
    ]
