# Generated by Django 4.0.3 on 2022-04-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('hobby', 'hobby'), ('food', 'food'), ('programming', 'programming')], default='hobby', max_length=100),
        ),
    ]
