# Generated by Django 4.0.3 on 2022-04-04 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_category_alter_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
