# Generated by Django 4.0.3 on 2022-04-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_remove_article_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.TextField(default='hobby'),
        ),
    ]
