# Generated by Django 4.1 on 2022-08-07 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_title', models.CharField(max_length=50)),
                ('Movie_content', models.TextField()),
                ('Movie_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movieauthor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovieComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_content', models.TextField()),
                ('M_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcauthor', to=settings.AUTH_USER_MODEL)),
                ('M_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moviecomments', to='Mapp.moviepost')),
            ],
        ),
        migrations.CreateModel(
            name='DramaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Drama_title', models.CharField(max_length=50)),
                ('Drama_content', models.TextField()),
                ('Drama_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dramaauthor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DramaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_content', models.TextField()),
                ('D_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcauthor', to=settings.AUTH_USER_MODEL)),
                ('D_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dramacomments', to='Mapp.dramapost')),
            ],
        ),
        migrations.CreateModel(
            name='BookPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_title', models.CharField(max_length=50)),
                ('Book_content', models.TextField()),
                ('Book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookauthor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B_content', models.TextField()),
                ('B_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bcauthor', to=settings.AUTH_USER_MODEL)),
                ('B_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookcomments', to='Mapp.bookpost')),
            ],
        ),
    ]
