# Generated by Django 4.1 on 2022-08-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpost',
            name='category',
            field=models.CharField(blank=True, choices=[('일반', '일반'), ('공지', '공지'), ('투표', '투표')], max_length=20),
        ),
        migrations.AddField(
            model_name='dramapost',
            name='category',
            field=models.CharField(blank=True, choices=[('일반', '일반'), ('공지', '공지'), ('투표', '투표')], max_length=20),
        ),
        migrations.AddField(
            model_name='moviepost',
            name='category',
            field=models.CharField(blank=True, choices=[('일반', '일반'), ('공지', '공지'), ('투표', '투표')], max_length=20),
        ),
    ]
