# Generated by Django 4.1 on 2022-08-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapp', '0002_bookpost_category_dramapost_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpost',
            name='category',
            field=models.CharField(blank=True, choices=[('일반', '일반'), ('서평', '서평'), ('공지', '공지'), ('투표', '투표')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dramapost',
            name='category',
            field=models.CharField(blank=True, choices=[('일반', '일반'), ('서평', '서평'), ('공지', '공지'), ('투표', '투표')], max_length=20),
        ),
        migrations.AlterField(
            model_name='moviepost',
            name='category',
            field=models.CharField(blank=True, choices=[('일반', '일반'), ('서평', '서평'), ('공지', '공지'), ('투표', '투표')], max_length=20),
        ),
    ]
