# Generated by Django 4.0.4 on 2022-05-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postapp', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
