# Generated by Django 4.0.5 on 2022-07-04 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_scrap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrap',
            old_name='user',
            new_name='author',
        ),
    ]
