# Generated by Django 4.0.5 on 2022-07-04 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_user_scrap_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrap',
            old_name='author',
            new_name='user',
        ),
    ]
